# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: debian:buster

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt update && apt -y install git libssl-dev g++ make curl libcurl4-gnutls-dev
    - pwd
    - curl -LO https://github.com/Kitware/CMake/releases/download/v3.20.0-rc5/cmake-3.20.0-rc5-linux-x86_64.sh
    - bash -c "yes | bash ./cmake-3.20.0-rc5-linux-x86_64.sh"
  script:
    - mkdir build
    - cd build
    - ../cmake-3.20.0-rc5-linux-x86_64/bin/cmake .. --config Release
    - make DESTDIR=./artifacts install
  artifacts:
    paths:
      - build/artifacts
